import "./globals.css";
import "instantsearch.css/themes/satellite-min.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul>
            <li>
              <Link href="/" prefetch={false}>
                Home Page (no search)
              </Link>
            </li>
            <li>
              <Link href="/algolia-search" prefetch={false}>
                Algolia Search
              </Link>
            </li>
            <li>
              <Link href="/typesense-search" prefetch={false}>
                Typesense Search (via adapter)
              </Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
